"""add deals

Revision ID: 3f18170ec07f
Revises: 4b44d1f070a0
Create Date: 2026-07-06 20:48:10.692120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f18170ec07f'
down_revision: Union[str, Sequence[str], None] = '4b44d1f070a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'NEGOTIATION', 'PROPOSAL', 'PAYMENT', 'WON', 'LOST', name='deal_stage'), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_amount'), 'deals', ['amount'], unique=False)
    op.create_index(op.f('ix_deals_client_id'), 'deals', ['client_id'], unique=False)
    op.create_index(op.f('ix_deals_created_by_id'), 'deals', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_responsible_id'), 'deals', ['responsible_id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_index(op.f('ix_deals_title'), 'deals', ['title'], unique=False)
    op.create_index(op.f('ix_deals_workspace_id'), 'deals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_deals_workspace_id"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_title"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_stage"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_responsible_id"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_id"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_created_by_id"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_client_id"),
        table_name="deals",
    )
    op.drop_index(
        op.f("ix_deals_amount"),
        table_name="deals",
    )

    op.drop_table("deals")

    sa.Enum(
        "NEW",
        "NEGOTIATION",
        "PROPOSAL",
        "PAYMENT",
        "WON",
        "LOST",
        name="deal_stage",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
